name: Generate Jars
on: [ push, pull_request ]
env:
  version: '1.20.1'
  branch: ver/1.20.1
jobs:
  paperclip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
      - name: Configure Git User Details
        run: |
            git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
            echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
      - name: Build Paperclip jar
        run: ./gradlew createReobfPaperclipJar --stacktrace
      - name: Upload Paperclip jar
        uses: actions/upload-artifact@v2
        with:
          name: kaiiju.jar
          path: build/libs/kaiiju-paperclip-*-reobf.jar
